
bitbucket:
    username: user.name
    password: password

env-ssh:
  username: user.name
  password: password

console:
  legacy: 
    username: mbadmin
    password: P455w0rd!
  digital: 
    username: user.name
    password: P455W0rd!
